### ISSUE TITLE
Needs more instructions - Can't get this to work

### ISSUE THREAD

**Issue by janeczku** [ggaughan/pipes-engine#1]
Obviously this only works with a outdated version of pipe2py. Unfortunately the README doesn't hint at what version this is compatible with.
E.g. main.py calls `pipe2py.compile.parse_and_write_pipe` which doesn't exist in the current version.
I tried to include a pipe2py version from August 2014. This results in the following error:

```
Traceback (most recent call last):
  File "/base/data/home/apps/e~feedpipr/3.386067089791421494/main.py", line 617, in main
    util.run_wsgi_app(application)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/webapp/util.py", line 99, in run_wsgi_app
    run_bare_wsgi_app(add_wsgi_middleware(application))
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/webapp/util.py", line 117, in run_bare_wsgi_app
    result = application(env, _start_response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~feedpipr/3.386067089791421494/main.py", line 274, in post
    source = pipe2py.compile.parse_and_write_pipe(context, pipe_def, ("pipe_%s" % pipe_id))
  File "/base/data/home/apps/e~feedpipr/3.386067089791421494/pipe2py/compile.py", line 437, in parse_and_write_pipe
    pipe = _parse_pipe(json_pipe, pipe_name)
  File "/base/data/home/apps/e~feedpipr/3.386067089791421494/pipe2py/compile.py", line 71, in _parse_pipe
    modules = json_pipe['modules']
TypeError: string indices must be integers
```

**Comment by ggaughan** [comment]
You might try pipe2py version 6a5c31eb218904a17800387bc4cd4239ba1b0b34. This is probably around the time I last ran it on GAE.
